services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: print_script_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5000:8080"
volumes:
    postgres_data:

