spring:
  application:
    name: print_script_service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}
stream:
  redis:
    stream:
      lint:
        key: ${STREAM_LINT_KEY:lint}
      format:
        key: ${STREAM_FORMAT_KEY:format}
      status:
        key: ${STREAM_STATUS_KEY:status}
    consumer:
      group: ${STREAM_CONSUMER_GROUP_PRINTSCRIPT:print-script-service}
auth0:
  audience: ${AUTH0_AUDIENCE}
logging:
  level:
    root: INFO
    com.printScript: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] - %msg%n"
